export { default as Query } from "./Query"
export { default as Mutation } from "./Mutation"
export { default as Customer } from "./Customer"
export { default as Appointment } from "./Appointment"
export { default as Subscription } from "./Subscription"
